module.exports = [
    {
        id: 980,
        title: 'Accountant',
        pid: null,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 981,
        title: 'Engineer',
        pid: 980,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 982,
        title: 'Manager',
        pid: 981,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 983,
        title: 'Analyst',
        pid: 980,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 984,
        title: 'Developer',
        pid: 983,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 985,
        title: 'Supervisor',
        pid: 982,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 986,
        title: 'Coordinator',
        pid: 985,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 987,
        title: 'Specialist',
        pid: 984,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 988,
        title: 'Officer',
        pid: 983,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 989,
        title: 'Administrator',
        pid: 988,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 990,
        title: 'Technician',
        pid: 981,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 991,
        title: 'Coordinator',
        pid: 986,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 992,
        title: 'Manager',
        pid: 990,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 993,
        title: 'Engineer',
        pid: 988,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 994,
        title: 'Officer',
        pid: 986,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 995,
        title: 'Supervisor',
        pid: 992,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 996,
        title: 'Analyst',
        pid: 985,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 997,
        title: 'Administrator',
        pid: 993,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 998,
        title: 'Technician',
        pid: 990,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 999,
        title: 'Developer',
        pid: 997,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1000,
        title: 'Coordinator',
        pid: 996,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1001,
        title: 'Engineer',
        pid: 994,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1002,
        title: 'Officer',
        pid: 989,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1003,
        title: 'Administrator',
        pid: 995,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1004,
        title: 'Supervisor',
        pid: 998,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1005,
        title: 'Manager',
        pid: 1003,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1006,
        title: 'Analyst',
        pid: 1005,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1007,
        title: 'Developer',
        pid: 994,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1008,
        title: 'Coordinator',
        pid: 996,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1009,
        title: 'Technician',
        pid: 989,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1010,
        title: 'Administrator',
        pid: 995,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1011,
        title: 'Engineer',
        pid: 987,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1012,
        title: 'Officer',
        pid: 1000,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1013,
        title: 'Manager',
        pid: 1008,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1014,
        title: 'Analyst',
        pid: 1007,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1015,
        title: 'Supervisor',
        pid: 1013,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1016,
        title: 'Developer',
        pid: 1011,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1017,
        title: 'Administrator',
        pid: 1014,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1018,
        title: 'Technician',
        pid: 1015,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1019,
        title: 'Coordinator',
        pid: 1004,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1020,
        title: 'Engineer',
        pid: 1019,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1021,
        title: 'Officer',
        pid: 1020,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1022,
        title: 'Manager',
        pid: 1009,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1023,
        title: 'Analyst',
        pid: 1016,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1024,
        title: 'Developer',
        pid: 1022,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1025,
        title: 'Supervisor',
        pid: 1021,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1026,
        title: 'Administrator',
        pid: 1018,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1027,
        title: 'Technician',
        pid: 1024,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1028,
        title: 'Coordinator',
        pid: 1017,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1029,
        title: 'Engineer',
        pid: 1025,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1030,
        title: 'Manager',
        pid: 1027,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1031,
        title: 'Officer',
        pid: 1023,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1032,
        title: 'Analyst',
        pid: 1028,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1033,
        title: 'Developer',
        pid: 1030,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1034,
        title: 'Supervisor',
        pid: 1026,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1035,
        title: 'Administrator',
        pid: 1029,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1036,
        title: 'Coordinator',
        pid: 1033,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1037,
        title: 'Technician',
        pid: 1035,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1038,
        title: 'Administrator',
        pid: 1031,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1039,
        title: 'Manager',
        pid: 1034,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1040,
        title: 'Analyst',
        pid: 1039,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1041,
        title: 'Developer',
        pid: 1036,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1042,
        title: 'Supervisor',
        pid: 1040,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1043,
        title: 'Engineer',
        pid: 1038,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1044,
        title: 'Officer',
        pid: 1042,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1045,
        title: 'Manager',
        pid: 1044,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1046,
        title: 'Coordinator',
        pid: 1045,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1047,
        title: 'Administrator',
        pid: 1043,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1048,
        title: 'Technician',
        pid: 1041,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1049,
        title: 'Developer',
        pid: 1046,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1050,
        title: 'Supervisor',
        pid: 1047,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1051,
        title: 'Analyst',
        pid: 1048,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1052,
        title: 'Engineer',
        pid: 1050,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1053,
        title: 'Officer',
        pid: 1052,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1054,
        title: 'Manager',
        pid: 1049,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 1055,
        title: 'Coordinator',
        pid: 1054,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
];
