module.exports = [
    {
        id: 980,
        title: 'CEO',
        pid: null,
        globalUserId: '652d4b7540739536088b3b39',
        name: 'JOSH OLCUCU',
        email: 'COSKUNOLCUCU+2@ICLOUD.COM',
        profileImage:
            'https://staging.users.api.maximumaccountability.net/api/v1/user/profileImage/652d4b7540739536088b3b39?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBTkFORC5WRVJNQSs1MDFAUVMyNTAwLkNPTSIsInVzZXJJZCI6IjY1MmQ0YmZhNDA3Mzk1MzYwODhiM2IzYiIsIm9pZCI6IjY1MmQ0YWQ1NDA3Mzk1MzYwODhiM2IzOCIsIm9uYW1lIjoiREVWIFRFQU0iLCJuYW1lIjoiQU5BTkQgVkVSTUEiLCJwcm9maWxlSW1hZ2UiOnRydWUsImlhdCI6MTcwNTY3NDQxNiwiZXhwIjoxNzA1NjkyNDE2fQ.mg9UJK4f6YWrSzkGzX2d598-6FlBLHoKBf4BURrz1r4',
        status: 1,
        departmentId: 41,
        departmentName: 'Finance',
        color: '#0F1ABA',
    },
    {
        id: 981,
        title: 'Finance',
        pid: 982,
        globalUserId: '652d4bcd40739536088b3b3a',
        name: 'DEEPAK KUMAR',
        email: 'DEEPAK.1999.KUMAR+1@GMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 45,
        departmentName: 'Purchasing',
        color: '#0D0C1C',
    },
    {
        id: 982,
        title: 'Dev',
        pid: 980,
        globalUserId: '652d4bfa40739536088b3b3b',
        name: 'ANAND VERMA',
        email: 'ANAND.VERMA+501@QS2500.COM',
        profileImage:
            'https://staging.users.api.maximumaccountability.net/api/v1/user/profileImage/652d4bfa40739536088b3b3b?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBTkFORC5WRVJNQSs1MDFAUVMyNTAwLkNPTSIsInVzZXJJZCI6IjY1MmQ0YmZhNDA3Mzk1MzYwODhiM2IzYiIsIm9pZCI6IjY1MmQ0YWQ1NDA3Mzk1MzYwODhiM2IzOCIsIm9uYW1lIjoiREVWIFRFQU0iLCJuYW1lIjoiQU5BTkQgVkVSTUEiLCJwcm9maWxlSW1hZ2UiOnRydWUsImlhdCI6MTcwNTY3NDQxNiwiZXhwIjoxNzA1NjkyNDE2fQ.mg9UJK4f6YWrSzkGzX2d598-6FlBLHoKBf4BURrz1r4',
        status: 1,
        departmentId: 43,
        departmentName: 'HR',
        color: '#1ADF1A',
    },
    {
        id: 990,
        title: 'Backend Dev',
        pid: 982,
        globalUserId: '652fe97b40739536088b3b46',
        name: 'GUS1 MICHOS',
        email: 'GUSMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 42,
        departmentName: 'IT',
        color: '#1AA59A',
    },
    {
        id: 991,
        title: 'Frontend Dev',
        pid: 982,
        globalUserId: '652fe9bd40739536088b3b47',
        name: 'PAUL MICHOS',
        email: 'PAULMICHOS@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 45,
        departmentName: 'Purchasing',
        color: '#0D0C1C',
    },
    {
        id: 992,
        title: 'Accounting',
        pid: 981,
        globalUserId: '652fe9fb40739536088b3b48',
        name: 'JOY SAMANGO',
        email: 'JOYSAMANGO@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 41,
        departmentName: 'Finance',
        color: '#0F1ABA',
    },
    {
        id: 993,
        title: 'Purchasing',
        pid: 981,
        globalUserId: '652fea5040739536088b3b49',
        name: 'YESIM GOKTEKIN',
        email: 'YESIMGOKTEKIN@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 43,
        departmentName: 'HR',
        color: '#1ADF1A',
    },
    {
        id: 998,
        title: 'Scrum Master',
        pid: 982,
        globalUserId: '653146932a7c386f20592842',
        name: 'MIKE KELLY',
        email: 'MIKEKELLY@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 43,
        departmentName: 'HR',
        color: '#1ADF1A',
    },
    {
        id: 999,
        title: 'Quality Assurance',
        pid: 982,
        globalUserId: '653147462a7c386f20592843',
        name: 'DONOVAN PIERCE',
        email: 'DONOVANPIERCE@YOPMAIL.COM',
        profileImage: '/img/user_info.png',
        status: 1,
        departmentId: 41,
        departmentName: 'Finance',
        color: '#0F1ABA',
    },
    {
        id: 1035,
        title: 'Accountant',
        pid: 992,
        globalUserId: '65552baae8839f8c908068f9',
        name: 'SELCUK DEMIR',
        email: 'SELCUKDEMIR@GMAIL.COM',
        profileImage: '/img/user_info.png',
        status: -2,
        departmentId: 45,
        departmentName: 'Purchasing',
        color: '#0D0C1C',
    },
];
